### ISSUE TITLE
Syntax and format for input file

### ISSUE THREAD

**Issue by remote2024** [galloty/genefer22#11]
Hello, are you able to provide the proper syntax and format for using GPU genefer22 with an input file from command line please? I have searched the web and tried many formats. A link to a PDF paper using genefer showed some syntax on a previous version but I could not get it to work. Is this a compile setting or am I just plain ignorant? Would appreciate your help and some CLI examples. Thank you.
re: Genefer: Programs for Finding Large Probable Generalized Fermat Primes, 2015
http://dx.doi.org/10.5334/jors.ca

**Comment by remote2024** [comment]
2nd question: is it possible to easily change the algorithm/calculation method for generating the test prime? e.g.
k * 2^n +/- 1
a  * 10^b +/- 1
10^x + y +/- 1
2^n + m +/- 1
... and to test for twin primes?

**Comment by galloty** [comment]
A batch/shell script can read a file and call genefer. For example, on Windows
```
@echo off
for /F "tokens=*" %%B in  (input.txt) do (
   genefer -n 17 -b %%B -q
)
```

The algorithm can be extended to the factors of the form *x*<sup>*n*</sup> - 1 (cyclotomic polynomials), where *n* is smooth.  
This project implements *b*<sup>2<sup>*n*</sup></sup> + 1 (genefer) and *b*<sup>2<sup>*n*</sup></sup> - *b*<sup>2<sup>*n* - 1</sup></sup>+ 1 (cyclo). The forms that you listed are not cyclotomic polynomials and cannot be tested using the algorithm of this project.
